{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "25fb45ef",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting git+https://github.com/kakaobrain/pororo.git\n",
      "  Cloning https://github.com/kakaobrain/pororo.git to c:\\users\\hi\\appdata\\local\\temp\\pip-req-build-551t3irg\n",
      "  Resolved https://github.com/kakaobrain/pororo.git to commit 7d05a75e8062b00e6b65364b8ec6c52b6293ab07\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "  Running command git clone -q https://github.com/kakaobrain/pororo.git 'C:\\Users\\hi\\AppData\\Local\\Temp\\pip-req-build-551t3irg'\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\ProgramData\\Anaconda3\\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-req-build-551t3irg\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-req-build-551t3irg\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\hi\\AppData\\Local\\Temp\\pip-pip-egg-info-j3dwghwu'\n",
      "         cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-req-build-551t3irg\\\n",
      "    Complete output (5 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-req-build-551t3irg\\setup.py\", line 33, in <module>\n",
      "        long_description=open(\"README.md\").read(),\n",
      "    UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 4914: illegal multibyte sequence\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding git+https://github.com/kakaobrain/pororo.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "# !pip install git+https://github.com/kakaobrain/pororo.git (이걸로 설치 x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "499297ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting python-mecab-ko\n",
      "  Downloading python-mecab-ko-1.0.12.tar.gz (9.7 kB)\n",
      "Collecting pybind11~=2.0\n",
      "  Downloading pybind11-2.9.2-py2.py3-none-any.whl (213 kB)\n",
      "Building wheels for collected packages: python-mecab-ko\n",
      "  Building wheel for python-mecab-ko (setup.py): started\n",
      "  Building wheel for python-mecab-ko (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for python-mecab-ko\n",
      "Failed to build python-mecab-ko\n",
      "Installing collected packages: pybind11, python-mecab-ko\n",
      "    Running setup.py install for python-mecab-ko: started\n",
      "    Running setup.py install for python-mecab-ko: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\ProgramData\\Anaconda3\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\hi\\AppData\\Local\\Temp\\pip-wheel-flu38bqk'\n",
      "       cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\n",
      "  Complete output (71 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build\\lib.win-amd64-3.7\n",
      "  creating build\\lib.win-amd64-3.7\\mecab\n",
      "  copying mecab\\mecab.py -> build\\lib.win-amd64-3.7\\mecab\n",
      "  copying mecab\\__init__.py -> build\\lib.win-amd64-3.7\\mecab\n",
      "  running build_ext\n",
      "  building '_mecab' extension\n",
      "  Traceback (most recent call last):\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 179, in <module>\n",
      "      'build_ext': BuildExtensionCommand\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 87, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 148, in setup\n",
      "      return run_commands(dist)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 163, in run_commands\n",
      "      dist.run_commands()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 967, in run_commands\n",
      "      self.run_command(cmd)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1214, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 986, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\wheel\\bdist_wheel.py\", line 299, in run\n",
      "      self.run_command('build')\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1214, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 986, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build.py\", line 135, in run\n",
      "      self.run_command(cmd_name)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\cmd.py\", line 313, in run_command\n",
      "      self.distribution.run_command(command)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1214, in run_command\n",
      "      super().run_command(command)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 986, in run_command\n",
      "      cmd_obj.run()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\command\\build_ext.py\", line 79, in run\n",
      "      _build_ext.run(self)\n",
      "    File \"C:\\Users\\hi\\AppData\\Roaming\\Python\\Python37\\site-packages\\Cython\\Distutils\\old_build_ext.py\", line 186, in run\n",
      "      _build_ext.build_ext.run(self)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build_ext.py\", line 339, in run\n",
      "      self.build_extensions()\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 43, in build_extensions\n",
      "      super().build_extensions()\n",
      "    File \"C:\\Users\\hi\\AppData\\Roaming\\Python\\Python37\\site-packages\\Cython\\Distutils\\old_build_ext.py\", line 195, in build_extensions\n",
      "      _build_ext.build_ext.build_extensions(self)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build_ext.py\", line 448, in build_extensions\n",
      "      self._build_extensions_serial()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build_ext.py\", line 473, in _build_extensions_serial\n",
      "      self.build_extension(ext)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\command\\build_ext.py\", line 202, in build_extension\n",
      "      _build_ext.build_extension(self, ext)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\command\\build_ext.py\", line 534, in build_extension\n",
      "      depends=ext.depends)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\_msvccompiler.py\", line 329, in compile\n",
      "      sources, depends, extra_postargs)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\ccompiler.py\", line 341, in _setup_compile\n",
      "      pp_opts = gen_preprocess_options(macros, incdirs)\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\ccompiler.py\", line 1083, in gen_preprocess_options\n",
      "      pp_opts.append(\"-I%s\" % dir)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 95, in __str__\n",
      "      return func(*self.args, **self.kwargs)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 108, in get_pybind_include\n",
      "      import pybind11\n",
      "  ModuleNotFoundError: No module named 'pybind11'\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for python-mecab-ko\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\ProgramData\\Anaconda3\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\hi\\AppData\\Local\\Temp\\pip-record-i2jjnlvw\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\ProgramData\\Anaconda3\\Include\\python-mecab-ko'\n",
      "         cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\n",
      "    Complete output (58 lines):\n",
      "    running install\n",
      "    C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\command\\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "      setuptools.SetuptoolsDeprecationWarning,\n",
      "    Installing mecab-ko...\n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\scripts\\install-mecab-ko.py\", line 72, in install\n",
      "        download(url)\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\scripts\\install-mecab-ko.py\", line 53, in download\n",
      "        ], check=True)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\subprocess.py\", line 472, in run\n",
      "        with Popen(*popenargs, **kwargs) as process:\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\subprocess.py\", line 775, in __init__\n",
      "        restore_signals, start_new_session)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\subprocess.py\", line 1178, in _execute_child\n",
      "        startupinfo)\n",
      "    FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\scripts\\install-mecab-ko.py\", line 80, in <module>\n",
      "        '--enable-utf8-only')\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\scripts\\install-mecab-ko.py\", line 74, in install\n",
      "        make()\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\tempfile.py\", line 805, in __exit__\n",
      "        self.cleanup()\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\tempfile.py\", line 809, in cleanup\n",
      "        _shutil.rmtree(self.name)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\shutil.py\", line 516, in rmtree\n",
      "        return _rmtree_unsafe(path, onerror)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\shutil.py\", line 404, in _rmtree_unsafe\n",
      "        onerror(os.rmdir, path, sys.exc_info())\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\shutil.py\", line 402, in _rmtree_unsafe\n",
      "        os.rmdir(path)\n",
      "    PermissionError: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다: 'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\tmpmcyjlm25'\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 179, in <module>\n",
      "        'build_ext': BuildExtensionCommand\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\__init__.py\", line 87, in setup\n",
      "        return distutils.core.setup(**attrs)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 148, in setup\n",
      "        return run_commands(dist)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\core.py\", line 163, in run_commands\n",
      "        dist.run_commands()\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 967, in run_commands\n",
      "        self.run_command(cmd)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\dist.py\", line 1214, in run_command\n",
      "        super().run_command(command)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\_distutils\\dist.py\", line 986, in run_command\n",
      "        cmd_obj.run()\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 76, in run\n",
      "        self.install_mecab()\n",
      "      File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-_7lynl26\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\setup.py\", line 85, in install_mecab\n",
      "        cwd=scripts_directory)\n",
      "      File \"C:\\ProgramData\\Anaconda3\\lib\\subprocess.py\", line 347, in check_call\n",
      "        raise CalledProcessError(retcode, cmd)\n",
      "    subprocess.CalledProcessError: Command '['C:\\\\ProgramData\\\\Anaconda3\\\\python.exe', 'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\scripts\\\\install-mecab-ko.py']' returned non-zero exit status 1.\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\ProgramData\\Anaconda3\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\hi\\\\AppData\\\\Local\\\\Temp\\\\pip-install-_7lynl26\\\\python-mecab-ko_3030e76ffa4643d7abac6ad9939feb22\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\hi\\AppData\\Local\\Temp\\pip-record-i2jjnlvw\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\ProgramData\\Anaconda3\\Include\\python-mecab-ko' Check the logs for full command output.\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "# !pip install python-mecab-ko"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "96fcaddc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pororo\n",
      "  Downloading pororo-0.4.2-py3-none-any.whl (256 kB)\n",
      "Collecting marisa-trie\n",
      "  Downloading marisa_trie-0.7.7-cp37-cp37m-win_amd64.whl (145 kB)\n",
      "Collecting fairseq>=0.10.2\n",
      "  Downloading fairseq-0.12.1.tar.gz (9.6 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading fairseq-0.12.0.tar.gz (9.6 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading fairseq-0.11.1.tar.gz (9.6 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading fairseq-0.10.2.tar.gz (938 kB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "Collecting pororo\n",
      "  Downloading pororo-0.4.1-py3-none-any.whl (253 kB)\n",
      "  Downloading pororo-0.4.0-py3-none-any.whl (253 kB)\n",
      "  Downloading pororo-0.3.5-py3-none-any.whl (253 kB)\n",
      "  Downloading pororo-0.3.4-py3-none-any.whl (216 kB)\n",
      "  Downloading pororo-0.3.3-py3-none-any.whl (215 kB)\n",
      "  Downloading pororo-0.3.2-py3-none-any.whl (212 kB)\n",
      "  Downloading pororo-0.3.1-py3-none-any.whl (211 kB)\n",
      "\n",
      "The conflict is caused by:\n",
      "    pororo 0.4.2 depends on fairseq>=0.10.2\n",
      "    pororo 0.4.1 depends on fairseq>=0.10.2\n",
      "    pororo 0.4.0 depends on fairseq>=0.10.2\n",
      "    pororo 0.3.5 depends on fairseq>=0.10.2\n",
      "    pororo 0.3.4 depends on fairseq>=0.10.2\n",
      "    pororo 0.3.3 depends on fairseq>=0.10.2\n",
      "    pororo 0.3.2 depends on fairseq>=0.10.2\n",
      "    pororo 0.3.1 depends on torch==1.6.0\n",
      "\n",
      "To fix this you could try to:\n",
      "1. loosen the range of package versions you've specified\n",
      "2. remove package versions to allow pip attempt to solve the dependency conflict\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmpomrb8mxk'\n",
      "       cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-ighetma2\\fairseq_b030c694d5f94383b134bba82c35cf6a\n",
      "  Complete output (18 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-0gkl1fu0\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 178, in get_requires_for_build_wheel\n",
      "      config_settings, requirements=['wheel'])\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-0gkl1fu0\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 159, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-0gkl1fu0\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 174, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 27, in <module>\n",
      "      version = write_version_py()\n",
      "    File \"setup.py\", line 18, in write_version_py\n",
      "      with open(os.path.join(\"fairseq\", \"version.txt\")) as f:\n",
      "  FileNotFoundError: [Errno 2] No such file or directory: 'fairseq\\\\version.txt'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d7/0f/b7043b451a97eb9b4cfb1b1e23e567b947d9d7bca542403228bd53b435fe/fairseq-0.12.1.tar.gz#sha256=69eb0fa48e6ac2e53a8f3c146c9fd9582d748cd1f5c920a0fb305ba69f8e0b4a (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmpomrb8mxk' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmpsm17jlok'\n",
      "       cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-ighetma2\\fairseq_d6e75794cf6b499eb22b14a65e596eda\n",
      "  Complete output (18 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-1pq8rgix\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 178, in get_requires_for_build_wheel\n",
      "      config_settings, requirements=['wheel'])\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-1pq8rgix\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 159, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-1pq8rgix\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 174, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 27, in <module>\n",
      "      version = write_version_py()\n",
      "    File \"setup.py\", line 18, in write_version_py\n",
      "      with open(os.path.join(\"fairseq\", \"version.txt\")) as f:\n",
      "  FileNotFoundError: [Errno 2] No such file or directory: 'fairseq\\\\version.txt'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/fe/98/78af0d86438fc36464791195c7fd8cb021417a3961fccdbabb18db52c5d9/fairseq-0.12.0.tar.gz#sha256=2803c31cb41f121e1b7b312a60f521a33f70360b49317ab19f6f41e59c356aad (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmpsm17jlok' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmpejv8gbx_'\n",
      "       cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-ighetma2\\fairseq_4a202154625b42ce84015e96efa3ae1e\n",
      "  Complete output (18 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-oxfq0504\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 178, in get_requires_for_build_wheel\n",
      "      config_settings, requirements=['wheel'])\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-oxfq0504\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 159, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-oxfq0504\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 174, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 27, in <module>\n",
      "      version = write_version_py()\n",
      "    File \"setup.py\", line 18, in write_version_py\n",
      "      with open(os.path.join(\"fairseq\", \"version.txt\")) as f:\n",
      "  FileNotFoundError: [Errno 2] No such file or directory: 'fairseq\\\\version.txt'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/2b/7c/44b138514088b440ad8b4269f3feb3e1216208a7f46143fd51eb577166de/fairseq-0.11.1.tar.gz#sha256=1a84cde1ae1f4632bb1a714669a08b02625d38198d693a03ab45788ab049861f (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmpejv8gbx_' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmp9zcg80hc'\n",
      "       cwd: C:\\Users\\hi\\AppData\\Local\\Temp\\pip-install-ighetma2\\fairseq_99ebf0afbba14e61961e45444fbea961\n",
      "  Complete output (31 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"setup.py\", line 214, in <module>\n",
      "      do_setup(package_data)\n",
      "    File \"setup.py\", line 191, in do_setup\n",
      "      zip_safe=False,\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-xtim2lue\\overlay\\Lib\\site-packages\\setuptools\\__init__.py\", line 86, in setup\n",
      "      _install_setup_requires(attrs)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-xtim2lue\\overlay\\Lib\\site-packages\\setuptools\\__init__.py\", line 80, in _install_setup_requires\n",
      "      dist.fetch_build_eggs(dist.setup_requires)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-xtim2lue\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 62, in fetch_build_eggs\n",
      "      raise SetupRequirementsError(specifier_list)\n",
      "  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-xtim2lue\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 178, in get_requires_for_build_wheel\n",
      "      config_settings, requirements=['wheel'])\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-xtim2lue\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 159, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"C:\\Users\\hi\\AppData\\Local\\Temp\\pip-build-env-xtim2lue\\overlay\\Lib\\site-packages\\setuptools\\build_meta.py\", line 174, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 217, in <module>\n",
      "      os.unlink(fairseq_examples)\n",
      "  PermissionError: [WinError 5] 액세스가 거부되었습니다: 'fairseq\\\\examples'\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/02/59/1f466d82d64482e2809a167e0067979c23057b3752e668537d5ff24453c9/fairseq-0.10.2.tar.gz#sha256=45b90d8ccc3f5a4623a523fe2d0465f54413d03fd1ec9a9d7af0461148ca1a68 (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: 'C:\\ProgramData\\Anaconda3\\python.exe' 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\in_process\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\hi\\AppData\\Local\\Temp\\tmp9zcg80hc' Check the logs for full command output.\n",
      "ERROR: Cannot install pororo==0.3.1, pororo==0.3.2, pororo==0.3.3, pororo==0.3.4, pororo==0.3.5, pororo==0.4.0, pororo==0.4.1 and pororo==0.4.2 because these package versions have conflicting dependencies.\n",
      "ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -llib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -umpy (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -rllib3 (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution - (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -ffi (c:\\programdata\\anaconda3\\lib\\site-packages)\n",
      "WARNING: Ignoring invalid distribution -erkzeug (c:\\programdata\\anaconda3\\lib\\site-packages)\n"
     ]
    }
   ],
   "source": [
    "# !pip install pororo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3fc7b022",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pororo'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_12804\\639728525.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0mpororo\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mPororo\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'pororo'"
     ]
    }
   ],
   "source": [
    "from pororo import Pororo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc03cfb1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
